CapaPresentacionTienda/Controllers/TiendaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using CapaEntidad;
using CapaNegocio;
using CapaEntidad.Paypal;
// VALIDACION DE SESIONES
using CapaPresentacionTienda.Filter;

namespace CapaPresentacionTienda.Controllers
{
    public class TiendaController : Controller
    {
        // GET: Tienda
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Test()
        {
            return View();
        }

        public ActionResult Productos()
        {
            return View();
        }


        public ActionResult Nosotros()
        {
            return View();
        }

        public ActionResult Contacto()
        {
            return View();
        }



        // VISTA DETALLES DE PRODUCTOS
        public ActionResult DetalleProducto(int idproducto = 0)
        {
            Producto oProducto = new Producto();
            oProducto = new CN_Producto().Listar().Where(p => p.IdProducto == idproducto).FirstOrDefault();

            if (oProducto != null)
            {
                oProducto.RutaImagen = oProducto.RutaImagen; // Usamos la ruta directamente
            }

            return View(oProducto);
        }

        // LISTAR TODAS LAS CATEGORIAS
        [HttpGet]
        public JsonResult ListaCategorias()
        {
            List<Categoria> lista  = new List<Categoria>();
            lista = new CN_Categoria().Listar();
            return Json(new { data = lista }, JsonRequestBehavior.AllowGet);

        }
        // LISTAR MARCAS POR CATEGORIA
        [HttpPost]
        public JsonResult ListaMarcaPorCategoria(int idcategoria)
        {
            List<Marca> lista = new List<Marca>();
            lista = new CN_Marca().ListarMarcaPorCategoria(idcategoria);
            return Json(new { data = lista }, JsonRequestBehavior.AllowGet);

        }
        // LISTAR TODOS LOS PRODUCTOS A MOSTRAR EN TIENDA
        [HttpPost]
        public JsonResult ListarProductos(int idcategoria, int idmarca)
        {
            List<Producto> lista = new List<Producto>();
            lista = new CN_Producto().Listar().Select(p => new Producto()
            {
                IdProducto = p.IdProducto,
                Nombre = p.Nombre,
                Descripcion = p.Descripcion,
                oMarca = p.oMarca,
                oCategoria = p.oCategoria,
                Precio = p.Precio,
                Stock = p.Stock,
                RutaImagen = p.RutaImagen, // modificacion ruta imagen
                Activo = p.Activo
            }).Where(p =>
                p.oCategoria.IdCategoria == (idcategoria == 0 ? p.oCategoria.IdCategoria : idcategoria) &&
                p.oMarca.IdMarca == (idmarca == 0 ? p.oMarca.IdMarca : idmarca) &&
                p.Stock > 0 && p.Activo == true
            ).ToList();

            var jsonresult = Json(new { data = lista }, JsonRequestBehavior.AllowGet);
            jsonresult.MaxJsonLength = int.MaxValue;
            return jsonresult;
        }

        // AGREGAR PRODUCTOS AL CARRITO
        [HttpPost]
        public JsonResult AgregarCarrito(int idproducto)
        {
            int idcliente = ((Cliente)Session["Cliente"]).IdCliente; // CONVERTIR LA VARIABLE DE SESION EN UN OBJETO CLIENTE
            bool existe = new CN_Carrito().ExisteCarrito(idcliente, idproducto);
            bool respuesta = false;
            string mensaje = string.Empty;
            if (existe)
            {
                mensaje = "Lo sentimos, el producto ya existe en el carrito de compras";
            }
            else
            {
                respuesta = new CN_Carrito().OperacionCarrito(idcliente, idproducto, true, out mensaje);
            }
            return Json(new { respuesta = respuesta , mensaje = mensaje }, JsonRequestBehavior.AllowGet);
        }

        // DEVOLVER CANTIDAD DE PRODUCTOS AGREGADOS AL CARRITO DE COMPRAS
        [HttpGet]
        public JsonResult CantidadEnCarrito()
        {
            int idcliente = ((Cliente)Session["Cliente"]).IdCliente; // CONVERTIR LA VARIABLE DE SESION EN UN OBJETO CLIENTE
            int cantidad = new CN_Carrito().CantidadEnCarrito(idcliente);
            return Json(new { cantidad = cantidad }, JsonRequestBehavior.AllowGet);
        }
        // LISTAR TODOS LOS PRODUCTOS AGREGADOS AL CARRITO DE COMPRAS CLIENTES
        [HttpPost]
        public JsonResult ListarProductosCarrito()
        {
            int idcliente = ((Cliente)Session["Cliente"]).IdCliente;
            List<Carrito> oLista = new List<Carrito>();
            oLista = new CN_Carrito().ListarProducto(idcliente).Select(listacompra => new Carrito()
            {
                oProducto = new Producto()
                {
                    IdProducto = listacompra.oProducto.IdProducto,
                    Nombre = listacompra.oProducto.Nombre,
                    oMarca = listacompra.oProducto.oMarca,
                    Precio = listacompra.oProducto.Precio,
                    RutaImagen = listacompra.oProducto.RutaImagen // Usamos la ruta directamente
                },
                Cantidad = listacompra.Cantidad
            }).ToList();

            return Json(new { data = oLista }, JsonRequestBehavior.AllowGet);
        }

        // GESTIONAR TODAS LAS OPERACIONES DE CARRITO DE COMPRAS CLIENTES
        [HttpPost]
        public JsonResult OperacionCarrito(int idproducto, bool sumar)
        {
            int idcliente = ((Cliente)Session["Cliente"]).IdCliente; // CONVERTIR LA VARIABLE DE SESION EN UN OBJETO CLIENTE
            bool respuesta = false;
            string mensaje = string.Empty;
            respuesta = new CN_Carrito().OperacionCarrito(idcliente, idproducto, sumar, out mensaje);
            return Json(new { respuesta = respuesta, mensaje = mensaje }, JsonRequestBehavior.AllowGet);
        }

        // ELIMINAR PRODUCTOS AGREGADOS EN CARRITO DE COMPRAS
        [HttpPost]
        public JsonResult EliminarCarrito(int idproducto) 
        {
            int idcliente = ((Cliente)Session["Cliente"]).IdCliente; // CONVERTIR LA VARIABLE DE SESION EN UN OBJETO CLIENTE   
            bool respuesta = false;
            string mensaje = string.Empty;
            respuesta = new CN_Carrito().EliminarCarrito(idcliente, idproducto);
            return Json(new { respuesta = respuesta, mensaje = mensaje }, JsonRequestBehavior.AllowGet);
        }

        // OBTENER LISTADO DE DEPARTAMENTOS
        [HttpPost]
        public JsonResult ObtenerDepartamento()
        {
            List<Departamento> oLista = new List<Departamento>();
            oLista = new CN_Ubicacion().ObtenerDepartamento();
            return Json(new { lista = oLista }, JsonRequestBehavior.AllowGet);
        }
        // OBTENER LISTADO DE MUNICIPIOS
        [HttpPost]
        public JsonResult ObtenerMunicipio(string iddepartamento)
        {
            List<Municipio> oLista = new List<Municipio>();
            oLista = new CN_Ubicacion().ObtenerMunicipio(iddepartamento);
            return Json(new { lista = oLista }, JsonRequestBehavior.AllowGet);
        }
        [ValidarSession]
        [Authorize]
        public ActionResult Carrito()
        {
            return View();
        }
        // PROCESAR PAGO Y FINALIZAR VENTA DE PRODUCTOS CARRITO DE COMPRAS
        [HttpPost]
        public async Task<JsonResult> ProcesarPago(List<Carrito> oListaCarrito, Venta oVenta)
        {
            decimal total = 0;
            DataTable detalle_venta = new DataTable();
            detalle_venta.Locale = new CultureInfo("es-SV");
            detalle_venta.Columns.Add("IdProducto", typeof(string));
            detalle_venta.Columns.Add("Cantidad", typeof(int));
            detalle_venta.Columns.Add("Total", typeof(decimal));
            // LISTA DE PRODUCTOS PARA PROCESAMIENTO DATOS PAYPAL
            List<Item> oListaItem = new List<Item>();
            foreach(Carrito oCarrito in oListaCarrito)
            {
                decimal subtotal = Convert.ToDecimal(oCarrito.Cantidad.ToString()) * oCarrito.oProducto.Precio;
                total += subtotal;
                oListaItem.Add(new Item()
                {
                    name = oCarrito.oProducto.Nombre,
                    quantity = oCarrito.Cantidad.ToString(),
                    unit_amount = new UnitAmount()
                    {
                        currency_code = "USD",
                        value = oCarrito.oProducto.Precio.ToString("G", new CultureInfo("es-SV"))
                    }
                });
                detalle_venta.Rows.Add(new object[]
                {
                    oCarrito.oProducto.IdProducto,
                    oCarrito.Cantidad,
                    subtotal
                });
            }
            PurchaseUnit purchaseUnit = new PurchaseUnit()
            {
                amount = new Amount()
                {
                    currency_code = "USD",
                    value = total.ToString("G", new CultureInfo("es-SV")),
                    breakdown = new Breakdown()
                    {
                        item_total = new ItemTotal()
                        {
                            currency_code = "USD",
                            value = total.ToString("G", new CultureInfo("es-SV")),
                        }
                    }
                },
                description = "Compra Online Articulos Mi Tienda Comercial En Linea",
                items = oListaItem
            };

            Checkout_Order oCheckOutOrder = new Checkout_Order()
            {
                intent = "CAPTURE",
                purchase_units = new List<PurchaseUnit>() { purchaseUnit },
                application_context = new ApplicationContext()
                {
                    brand_name = "MIURL.COM",

CapaPresentacionTienda/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Vinos Ecommerce</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <!-- Incluir Google Fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Oswald:wght@200&display=swap" rel="stylesheet">

    <style>
        body {
            background-color: black;
            font-family: 'Oswald', Arial, Tahoma, Verdana;
        }

        .nav-link:hover {
            color: #b20932 !important;
        }

        .btn-outline-light:hover {
            background-color: #b20932 !important;
            border-color: #b20932 !important;
            color: #fff !important;
        }

        .tituloMenu {
            color: #b20932 !important
        }

        .navbar-toggler-icon {
            background-image: url("data:image/svg+xml;charset=utf8,%3Csvg viewBox='0 0 30 30' xmlns='http://www.w3.org/2000/svg'%3E%3Cpath stroke='rgba%28255, 255, 255, 1%29' stroke-width='2' stroke-linecap='round' stroke-miterlimit='10' d='M4 7h22M4 15h22M4 23h22'/%3E%3C/svg%3E");
        }
    </style>
</head>
<body class="d-flex flex-column min-vh-100">
    <!-- Navigation-->
    <nav class="navbar navbar-expand-lg shadow-sm">
        <div class="container">
            <a class="navbar-brand fw-bold text-uppercase tituloMenu" href="#!">Vino Ecommerce</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                    <li class="nav-item"><a class="nav-link text-light" href="@Url.Action("Index","Tienda")">Inicio</a></li>
                    <li class="nav-item"><a class="nav-link text-light" href="@Url.Action("Productos","Tienda")">Productos</a></li>
                    <li class="nav-item"><a class="nav-link text-light" href="@Url.Action("Contacto","Tienda")">Contacto</a></li>
                    <li class="nav-item"><a class="nav-link text-light" href="@Url.Action("Nosotros","Tienda")">Nosotros</a></li>
                </ul>
                <form class="d-flex align-items-center">
                    @if (Session["Cliente"] == null)
                    {
                        // CLIENTE NO HA INICIADO SESION
                        <a class="btn btn-outline-light" aria-current="page" href="@Url.Action("Index","Acceso")"><i class="fas fa-house-user me-1"></i> Iniciar Sesi&oacute;n</a>
                    }
                    else
                    {
                        // CLIENTE HA INICIADO SESION
                        <a class="btn btn-outline-light btn-sm me-2" href="@Url.Action("Carrito","Tienda")">
                            <i class="fas fa-shopping-cart me-1"></i>
                            Mi Carrito
                            <span class="badge bg-light text-dark ms-1" id="cantidadcarrito">0</span>
                        </a>
                        <ul class="navbar-nav ms-auto me-0 me-md-3 my-2 my-md-0">
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="fas fa-user fa-fw text-light"></i></a>
                                <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                                    <li><a class="dropdown-item" href="#">@User.Identity.Name</a></li>
                                    <li><a class="dropdown-item" href="@Url.Action("MisCompras","Tienda")">Mis Compras</a></li>
                                    <li><hr class="dropdown-divider" /></li>
                                    <li><a class="dropdown-item" href="@Url.Action("CerrarSesion","Acceso")">Cerrar Sesi&oacute;n</a></li>
                                </ul>
                            </li>
                        </ul>
                    }
                </form>
            </div>
        </div>
    </nav>

    @RenderBody()

    <footer class="text-center text-lg-start text-white"
            style="background-color: #333 ">
        <section class="d-flex justify-content-between p-4"
                 style="background-color: #000000 ">
            <div class="me-5">
                <span>Conectate a nuesras redes sociales:</span>
            </div>
            <div>
                <a href="" class="text-white me-4">
                    <i class="fab fa-facebook-f"></i>
                </a>
                <a href="" class="text-white me-4">
                    <i class="fab fa-twitter"></i>
                </a>
                <a href="" class="text-white me-4">
                    <i class="fab fa-google"></i>
                </a>
                <a href="" class="text-white me-4">
                    <i class="fab fa-instagram"></i>
                </a>
                <a href="" class="text-white me-4">
                    <i class="fab fa-linkedin"></i>
                </a>
                <a href="" class="text-white me-4">
                    <i class="fab fa-github"></i>
                </a>
            </div>
        </section>
        <section class="">
            <div class="container text-center text-md-start mt-5">
                <div class="row mt-3">
                    <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
                        <h6 class="text-uppercase fw-bold">Viña Éterna</h6>
                        <hr class="mb-4 mt-0 d-inline-block mx-auto"
                            style="width: 60px; background-color: #7c4dff; height: 2px" />
                        <p>
                            Donde la tradición y la excelencia se encuentran en cada botella. 
                            Descubre nuestros vinos cuidadosamente elaborados para deleitar 
                            los sentidos y convertir cada momento en una experiencia inolvidable. 🍷
                        </p>
                    </div>
                    <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
                        <h6 class="text-uppercase fw-bold">Productos</h6>
                        <hr class="mb-4 mt-0 d-inline-block mx-auto"
                            style="width: 60px; background-color: #7c4dff; height: 2px" />
                        <p>
                            <a href="#!" class="text-white">Categoria 1</a>
                        </p>
                        <p>
                            <a href="#!" class="text-white">Categoria 2</a>
                        </p>
                        <p>
                            <a href="#!" class="text-white">Categoria 3</a>
                        </p>
                        <p>
                            <a href="#!" class="text-white">Categoria 4</a>
                        </p>
                    </div>
                    <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
                        <h6 class="text-uppercase fw-bold">Links Recomendados</h6>
                        <hr class="mb-4 mt-0 d-inline-block mx-auto"
                            style="width: 60px; background-color: #7c4dff; height: 2px" />
                        <p>
                            <a href="#!" class="text-white">Nosotros</a>
                        </p>
                        <p>
                            <a href="#!" class="text-white">Terminos y Condiciones</a>
                        </p>
                        <p>
                            <a href="#!" class="text-white">Carrito</a>
                        </p>
                        <p>
                            <a href="#!" class="text-white">Ayuda</a>
                        </p>
                    </div>
                    <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
                        <h6 class="text-uppercase fw-bold">Contacto</h6>
                        <hr class="mb-4 mt-0 d-inline-block mx-auto"
                            style="width: 60px; background-color: #7c4dff; height: 2px" />
                        <p><i class="fas fa-home mr-3"></i> New York, NY 10012, US</p>
                        <p><i class="fas fa-envelope mr-3"></i> info@example.com</p>
                        <p><i class="fas fa-phone mr-3"></i> + 01 234 567 88</p>
                        <p><i class="fas fa-print mr-3"></i> + 01 234 567 89</p>
                    </div>
                </div>
            </div>
        </section>

        <div class="text-center p-3"
             style="background-color: rgba(0, 0, 0, 0.2)">
            © 2020 Copyright:
            <a class="text-white" href="https://mdbootstrap.com/">MDBootstrap.com</a>
        </div>

    </footer>







    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

    <script>
        $(document).ready(function () {
            MostrarCantidadCarrito();
        });
        // MOSTRAR CANTIDAD DE PRODUCTOS AGREGADOS EN EL CARRITO DE COMPRAS
        function MostrarCantidadCarrito() {
            if ($("#cantidadcarrito").length > 0) {
                jQuery.ajax({
                    url: '@Url.Action("CantidadEnCarrito","Tienda")',
                    type: 'get',
                    dataType: 'json',
                    contentType: "application/json; charset=utf-8",
                    success: function (data) {
                        $("#cantidadcarrito").text(data.cantidad);
                    }
                });
            }
        }
    </script>

</body>
</html>