CapaPresentacionAdministrador/Controllers/VentasController.cs
using CapaNegocio;
using CapaEntidad;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CapaPresentacionAdministrador.Controllers
{
    public class VentasController : Controller
    {
        private CN_Venta objNegocio = new CN_Venta();
        [HttpGet]
        public ActionResult ListaVentas()
        {
            List<Venta> oLista = new List<Venta>();
            oLista = new CN_Venta().Listar();
            return View(oLista);
        }



        public ActionResult DetalleVenta(int id)
        {
            List<DetalleVenta> oLista = new List<DetalleVenta>();
            oLista = new CN_Venta().ListarCompras(id);
            return View(oLista);
        }
    }
}

CapaPresentacionAdministrador/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="~/Content/sb-admin-2.css" rel="stylesheet" />
    <link href="/Content/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
          rel="stylesheet">

</head>


<body id="page-top">
    <div id="wrapper">

        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center" href="@Url.Action("Index","Home")">
                <div class="sidebar-brand-icon rotate-n-15">
                    <i class="fas fa-laugh-wink"></i>
                </div>
                <div class="sidebar-brand-text mx-3">Vinos</div>
            </a>

            <!-- Divider -->
            <hr class="sidebar-divider my-0">

            <!-- Nav Item - Dashboard -->
            <li class="nav-item active">
                <a class="nav-link" href="@Url.Action("Index","Home")">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Dashboard</span>
                </a>
            </li>

            <!-- Nav Item - Charts -->
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("ListaUsuarios","Usuario")">
                    <i class="fas fa-fw fa-chart-area"></i>
                    <span>Usuarios</span>
                </a>
            </li>

            <!-- Nav Item - Tables -->
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("ListaCategorias","Categoria")">
                    <i class="fas fa-fw fa-table"></i>
                    <span>Categorias</span>
                </a>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("ListaMarcas","Marca")">
                    <i class="fas fa-fw fa-table"></i>
                    <span>Marca</span>
                </a>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("ListaVentas","Ventas")">
                    <i class="fas fa-fw fa-table"></i>
                    <span>Ventas</span>
                </a>
            </li>


            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("ListaProductos","Producto")">
                    <i class="fas fa-fw fa-table"></i>
                    <span>Productos</span>
                </a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider d-none d-md-block">

            <!-- Sidebar Toggler (Sidebar) -->
            <div class="text-center d-none d-md-inline">
                <button class="rounded-circle border-0" id="sidebarToggle"></button>
            </div>



        </ul>
        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">
                    <!-- Sidebar Toggle (Topbar) -->
                    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                        <i class="fa fa-bars"></i>
                    </button>
                    <div class="ml-auto d-flex align-items-center">
                        <a class="btn btn-success mr-2" href="http://localhost:44351">Ir a tienda</a>
                        
                        <a class="btn btn-danger" href="@Url.Action("index","AccesoAdmin")">Cerrar Sesión</a>
                    </div>


                </nav>

                <div class="container-fluid">
                    @RenderBody()
                </div>


            </div>


        </div>


    </div>







    <!--
     <li>@Html.ActionLink("Inicio", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
     <li>@Html.ActionLink("Acerca de", "About", "Home", new { area = "" }, new { @class = "nav-link" })</li>
     <li>@Html.ActionLink("Contacto", "Contact", "Home", new { area = "" }, new { @class = "nav-link" })</li> -->




    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <script src="~/Scripts/vendor/jquery/jquery.min.js"></script>
    <script src="~/Scripts/js/sb-admin-2.min.js"></script>

    @RenderSection("scripts", required: false)
</body>
</html>